## Word Embedding Techniques Using Embedding layer in Keras

In [1]:
### use tensorflow > 2.0 and keras

In [2]:
# pip install tensorflow-gpu

In [3]:
import tensorflow as tf

2025-03-29 13:34:04.396673: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-29 13:34:04.962560: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-29 13:34:04.963010: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-29 13:34:05.071653: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-29 13:34:05.263447: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-29 13:34:05.265564: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [4]:
print(tf.__version__)

2.15.0


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your video are good',
]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your video are good']

In [8]:
### vocabulary size
voc_size = 10000

## One Hot Representation

In [9]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr)

[[4045, 7680, 9427, 9142], [4045, 7680, 9427, 5027], [4045, 2362, 9427, 9534], [1086, 1044, 7311, 8749, 3413], [1086, 1044, 7311, 8749, 4226], [766, 4045, 137, 9427, 6544], [6740, 55, 4306, 8749]]


## Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [16]:
## pre padding
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 4045 7680 9427 9142]
 [   0    0    0    0 4045 7680 9427 5027]
 [   0    0    0    0 4045 2362 9427 9534]
 [   0    0    0 1086 1044 7311 8749 3413]
 [   0    0    0 1086 1044 7311 8749 4226]
 [   0    0    0  766 4045  137 9427 6544]
 [   0    0    0    0 6740   55 4306 8749]]


In [18]:
# feature dimension
dim =10

In [19]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
# 'the glass of milk',
embedded_docs[0]

array([   0,    0,    0,    0, 4045, 7680, 9427, 9142], dtype=int32)

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 79ms/step


array([[ 0.04580306,  0.00843972,  0.03769448, -0.02947023,  0.02010033,
         0.03293467, -0.0167812 ,  0.02416671, -0.02579198, -0.02416637],
       [ 0.04580306,  0.00843972,  0.03769448, -0.02947023,  0.02010033,
         0.03293467, -0.0167812 ,  0.02416671, -0.02579198, -0.02416637],
       [ 0.04580306,  0.00843972,  0.03769448, -0.02947023,  0.02010033,
         0.03293467, -0.0167812 ,  0.02416671, -0.02579198, -0.02416637],
       [ 0.04580306,  0.00843972,  0.03769448, -0.02947023,  0.02010033,
         0.03293467, -0.0167812 ,  0.02416671, -0.02579198, -0.02416637],
       [ 0.04582038, -0.02206369, -0.03706963,  0.02449569, -0.03137424,
        -0.01894786,  0.01373782,  0.01247355,  0.02670659, -0.02693062],
       [-0.04207116, -0.01250546, -0.02565898, -0.03403936, -0.04570801,
        -0.04798813,  0.00367696, -0.0221377 ,  0.04556371,  0.02509278],
       [-0.02474871, -0.03481961, -0.03843129, -0.04031978,  0.00141771,
        -0.02096736,  0.01351049, -0.00301038

In [24]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 40ms/step


array([[[ 0.04580306,  0.00843972,  0.03769448, -0.02947023,
          0.02010033,  0.03293467, -0.0167812 ,  0.02416671,
         -0.02579198, -0.02416637],
        [ 0.04580306,  0.00843972,  0.03769448, -0.02947023,
          0.02010033,  0.03293467, -0.0167812 ,  0.02416671,
         -0.02579198, -0.02416637],
        [ 0.04580306,  0.00843972,  0.03769448, -0.02947023,
          0.02010033,  0.03293467, -0.0167812 ,  0.02416671,
         -0.02579198, -0.02416637],
        [ 0.04580306,  0.00843972,  0.03769448, -0.02947023,
          0.02010033,  0.03293467, -0.0167812 ,  0.02416671,
         -0.02579198, -0.02416637],
        [ 0.04582038, -0.02206369, -0.03706963,  0.02449569,
         -0.03137424, -0.01894786,  0.01373782,  0.01247355,
          0.02670659, -0.02693062],
        [-0.04207116, -0.01250546, -0.02565898, -0.03403936,
         -0.04570801, -0.04798813,  0.00367696, -0.0221377 ,
          0.04556371,  0.02509278],
        [-0.02474871, -0.03481961, -0.03843129, -0.0